import { SleepSession } from '../constants/Types';

// Demo sleep data for testing and demonstration
export const DEMO_SLEEP_DATA: SleepSession[] = [
  {
    id: '1',
    date: '2025-10-17',
    startTime: '23:47:00',
    endTime: '07:23:00',
    totalDurationMinutes: 456,
    sleepQuality: 'good',
    wakeUps: 2,
    remCycles: [
      {
        cycleNumber: 1,
        startTime: '00:45:00',
        durationMinutes: 18,
        isInterrupted: false,
        isPrimaryDream: false,
      },
      {
        cycleNumber: 2,
        startTime: '02:30:00',
        durationMinutes: 22,
        isInterrupted: false,
        isPrimaryDream: true,
      },
      {
        cycleNumber: 3,
        startTime: '04:15:00',
        durationMinutes: 25,
        isInterrupted: true,
        isPrimaryDream: false,
      },
      {
        cycleNumber: 4,
        startTime: '05:50:00',
        durationMinutes: 28,
        isInterrupted: false,
        isPrimaryDream: true,
      },
    ],
    stages: [
      { type: 'Awake', startTime: '23:47:00', durationMinutes: 12 },
      { type: 'Core', startTime: '23:59:00', durationMinutes: 35 },
      { type: 'Deep', startTime: '00:34:00', durationMinutes: 52 },
      { type: 'REM', startTime: '01:26:00', durationMinutes: 18 },
      { type: 'Core', startTime: '01:44:00', durationMinutes: 45 },
      { type: 'Deep', startTime: '02:29:00', durationMinutes: 38 },
      { type: 'REM', startTime: '03:07:00', durationMinutes: 22 },
      { type: 'Core', startTime: '03:29:00', durationMinutes: 40 },
      { type: 'Awake', startTime: '04:09:00', durationMinutes: 5 },
      { type: 'Core', startTime: '04:14:00', durationMinutes: 35 },
      { type: 'REM', startTime: '04:49:00', durationMinutes: 25 },
      { type: 'Core', startTime: '05:14:00', durationMinutes: 30 },
      { type: 'REM', startTime: '05:44:00', durationMinutes: 28 },
      { type: 'Core', startTime: '06:12:00', durationMinutes: 45 },
      { type: 'Awake', startTime: '06:57:00', durationMinutes: 26 },
    ],
    heartRateData: {
      restingBPM: 58,
      averageBPM: 62,
      minBPM: 54,
      maxBPM: 78,
      spikes: [
        {
          time: '02:45:00',
          bpm: 75,
          percentageAboveBaseline: 29,
          context: 'During intense REM dream sequence',
        },
        {
          time: '04:12:00',
          bpm: 78,
          percentageAboveBaseline: 34,
          context: 'Brief awakening after nightmare',
        },
        {
          time: '05:58:00',
          bpm: 72,
          percentageAboveBaseline: 24,
          context: 'Vivid dream with emotional content',
        },
      ],
    },
  },
  {
    id: '2',
    date: '2025-10-16',
    startTime: '23:15:00',
    endTime: '06:45:00',
    totalDurationMinutes: 450,
    sleepQuality: 'excellent',
    wakeUps: 1,
    remCycles: [
      {
        cycleNumber: 1,
        startTime: '00:30:00',
        durationMinutes: 20,
        isInterrupted: false,
        isPrimaryDream: false,
      },
      {
        cycleNumber: 2,
        startTime: '02:15:00',
        durationMinutes: 24,
        isInterrupted: false,
        isPrimaryDream: true,
      },
      {
        cycleNumber: 3,
        startTime: '04:00:00',
        durationMinutes: 26,
        isInterrupted: false,
        isPrimaryDream: true,
      },
      {
        cycleNumber: 4,
        startTime: '05:35:00',
        durationMinutes: 30,
        isInterrupted: false,
        isPrimaryDream: false,
      },
    ],
    stages: [
      { type: 'Awake', startTime: '23:15:00', durationMinutes: 8 },
      { type: 'Core', startTime: '23:23:00', durationMinutes: 42 },
      { type: 'Deep', startTime: '00:05:00', durationMinutes: 55 },
      { type: 'REM', startTime: '01:00:00', durationMinutes: 20 },
      { type: 'Core', startTime: '01:20:00', durationMinutes: 48 },
      { type: 'Deep', startTime: '02:08:00', durationMinutes: 45 },
      { type: 'REM', startTime: '02:53:00', durationMinutes: 24 },
      { type: 'Core', startTime: '03:17:00', durationMinutes: 38 },
      { type: 'Deep', startTime: '03:55:00', durationMinutes: 32 },
      { type: 'REM', startTime: '04:27:00', durationMinutes: 26 },
      { type: 'Core', startTime: '04:53:00', durationMinutes: 35 },
      { type: 'REM', startTime: '05:28:00', durationMinutes: 30 },
      { type: 'Core', startTime: '05:58:00', durationMinutes: 40 },
      { type: 'Awake', startTime: '06:38:00', durationMinutes: 7 },
    ],
    heartRateData: {
      restingBPM: 56,
      averageBPM: 59,
      minBPM: 52,
      maxBPM: 71,
      spikes: [
        {
          time: '02:28:00',
          bpm: 68,
          percentageAboveBaseline: 21,
          context: 'Moderate dream activity',
        },
        {
          time: '04:42:00',
          bpm: 71,
          percentageAboveBaseline: 27,
          context: 'Intense vivid dream scenario',
        },
      ],
    },
  },
  {
    id: '3',
    date: '2025-10-15',
    startTime: '00:10:00',
    endTime: '08:05:00',
    totalDurationMinutes: 475,
    sleepQuality: 'fair',
    wakeUps: 4,
    remCycles: [
      {
        cycleNumber: 1,
        startTime: '01:05:00',
        durationMinutes: 15,
        isInterrupted: true,
        isPrimaryDream: false,
      },
      {
        cycleNumber: 2,
        startTime: '02:50:00',
        durationMinutes: 20,
        isInterrupted: false,
        isPrimaryDream: true,
      },
      {
        cycleNumber: 3,
        startTime: '04:40:00',
        durationMinutes: 18,
        isInterrupted: true,
        isPrimaryDream: false,
      },
      {
        cycleNumber: 4,
        startTime: '06:25:00',
        durationMinutes: 24,
        isInterrupted: false,
        isPrimaryDream: false,
      },
    ],
    stages: [
      { type: 'Awake', startTime: '00:10:00', durationMinutes: 15 },
      { type: 'Core', startTime: '00:25:00', durationMinutes: 38 },
      { type: 'Deep', startTime: '01:03:00', durationMinutes: 42 },
      { type: 'REM', startTime: '01:45:00', durationMinutes: 15 },
      { type: 'Awake', startTime: '02:00:00', durationMinutes: 8 },
      { type: 'Core', startTime: '02:08:00', durationMinutes: 40 },
      { type: 'Deep', startTime: '02:48:00', durationMinutes: 35 },
      { type: 'REM', startTime: '03:23:00', durationMinutes: 20 },
      { type: 'Core', startTime: '03:43:00', durationMinutes: 45 },
      { type: 'Awake', startTime: '04:28:00', durationMinutes: 12 },
      { type: 'Core', startTime: '04:40:00', durationMinutes: 35 },
      { type: 'REM', startTime: '05:15:00', durationMinutes: 18 },
      { type: 'Core', startTime: '05:33:00', durationMinutes: 48 },
      { type: 'REM', startTime: '06:21:00', durationMinutes: 24 },
      { type: 'Core', startTime: '06:45:00', durationMinutes: 50 },
      { type: 'Awake', startTime: '07:35:00', durationMinutes: 30 },
    ],
    heartRateData: {
      restingBPM: 60,
      averageBPM: 65,
      minBPM: 56,
      maxBPM: 82,
      spikes: [
        {
          time: '02:05:00',
          bpm: 79,
          percentageAboveBaseline: 32,
          context: 'Interrupted REM, brief awakening',
        },
        {
          time: '03:38:00',
          bpm: 76,
          percentageAboveBaseline: 27,
          context: 'Stressful dream content',
        },
        {
          time: '04:30:00',
          bpm: 82,
          percentageAboveBaseline: 37,
          context: 'Nightmare awakening',
        },
        {
          time: '06:35:00',
          bpm: 73,
          percentageAboveBaseline: 22,
          context: 'Final REM cycle activity',
        },
      ],
    },
  },
];

